project:
  type: website
  output-dir: docs

website:
  title: "Wide baseline stereo meets deep learning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ducha_aiki
      - icon: twitter
        href: https://twitter.com/ducha_aiki
  body-footer: | 
    Everything you (didn't) want to know about image matching
  google-analytics: "G-GE2NZRSZBN"
format:
  html:
    theme: cosmo
    css: styles.css